kind: pipeline
name: lccs-ws

steps:
- name: build
  image: python:3.7
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - lccs_db db init
  - lccs_db db create-namespaces
  - lccs_db alembic upgrade
  - lccs_db db load-scripts
  - ./run-tests.sh
  environment:
    SQLALCHEMY_DATABASE_URI: postgresql://postgres:mysecretpassword@pg_database:5432/bdc_db

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

- name: docker-registry
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    registry: registry.dpi.inpe.br
    repo: registry.dpi.inpe.br/${DRONE_REPO}
    custom_dns: 150.163.2.4


- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success

services:
- name: pg_database
  image: postgis/postgis:13-3.1
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres