#
# This file is part of Land Cover Classification System Web Service.
# Copyright (C) 2019 INPE.
#
# Land Cover Classification System Web Service is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3.3'

networks:
  bdc_net:

services:
  lccs-ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: lccs-ws
    image: lccs-ws:0.4.0-0
    restart: "always"
    environment:
      - "SQLALCHEMY_DATABASE_URI=postgresql://user:password@localhost:5432/dbname"
      - "LCCS_URL=http://localhost:8080"
    networks:
      - bdc_net
    ports:
      - "127.0.0.1:8080:5000"